project_id = "supabase-local"

[api]
port = 8100
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5433
shadow_port = 5434

[auth]
site_url = "http://localhost:3000"

[storage]
enabled = true
